name: Deploy to Hostinger

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # البuild في الـ root مباشرة
      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      # رفع الـ Next.js build على public_html/new
      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: public_html/new/
          exclude: |
            **/.git*
            **/node_modules/**
            **/.next/cache/**
            **/prisma/**
            **/*.md
